# Simple Neural Network with One Hidden Layer

This notebook demonstrates a simple neural network and explains how data flows from input to output during training.

## 1. Import Libraries

In [1]:
import numpy as np

## 2. Create Input Data

Example dataset similar to XOR problem.

In [2]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

print("Input Data:")
print(X)

print("Expected Output:")
print(y)

Input Data:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Expected Output:
[[0]
 [1]
 [1]
 [0]]


## 3. Initialize Weights

Weights connect neurons between layers.

In [3]:
np.random.seed(1)

weights_input_hidden = np.random.rand(2,3)
weights_hidden_output = np.random.rand(3,1)

print("Weights (Input -> Hidden):")
print(weights_input_hidden)

print("Weights (Hidden -> Output):")
print(weights_hidden_output)

Weights (Input -> Hidden):
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]
Weights (Hidden -> Output):
[[0.18626021]
 [0.34556073]
 [0.39676747]]


## 4. Define Activation Function

We use the **Sigmoid function** to convert values between 0 and 1.

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

## 5. Training the Neural Network

Training involves:

1. Forward Propagation
2. Calculating Prediction
3. Updating Weights (concept of backpropagation)

In [6]:
for epoch in range(1000):

    # Forward Propagation
    hidden_input = np.dot(X, weights_input_hidden)
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output)
    predicted_output = sigmoid(final_input)

print("Predicted Output After Training:")
print(predicted_output)

Predicted Output After Training:
[[0.61403239]
 [0.62247681]
 [0.63253756]
 [0.64017496]]


## 6. Explanation of Data Flow

### Step 1: Input Layer
The input layer receives the data.  
Example inputs: (0,0), (0,1), (1,0), (1,1).

### Step 2: Hidden Layer
Input values are multiplied by weights and passed to the hidden layer.

Hidden layer formula:

H = sigmoid(X × W1)

### Step 3: Output Layer
Hidden layer outputs are multiplied by another set of weights.

Output formula:

Y = sigmoid(H × W2)

### Step 4: Prediction
The final output is the predicted result.

### Step 5: Training
During training, the network adjusts weights to reduce prediction error.

## 7. Conclusion

A simple neural network with one hidden layer processes data through multiple layers.  
During training, the network learns patterns by adjusting weights based on prediction errors.  

This process allows the model to improve its predictions over time.