In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# 1. Prepare sample data
# Let's create a simple dataset for demonstration, similar to XOR problem but simpler
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=np.float32)

y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=np.float32)

print("Input data (X):\n", X)
print("Target data (y):\n", y)

# 2. Build the neural network model
model = Sequential([
    # Input layer and first hidden layer (2 neurons, relu activation)
    Dense(2, activation='relu', input_shape=(2,)),
    # Second hidden layer (2 neurons, relu activation)
    Dense(2, activation='relu'),
    # Output layer (1 neuron, sigmoid activation for binary classification)
    Dense(1, activation='sigmoid')
])

# 3. Compile the model
# Optimizer: Adam (an efficient gradient descent algorithm)
# Loss function: Binary Crossentropy (common for binary classification)
# Metrics: Accuracy (to monitor performance)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Display the model's architecture
model.summary()

# 4. Train the model
print("\nTraining the model...")
history = model.fit(X, y, epochs=1000, verbose=0) # Train for 1000 epochs, no verbose output

# 5. Evaluate the model
loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"\nModel Evaluation - Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

# 6. Make predictions
predictions = model.predict(X)
print("\nPredictions:\n", predictions.round())


Input data (X):
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Target data (y):
 [[0.]
 [1.]
 [1.]
 [0.]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)


Training the model...

Model Evaluation - Loss: 0.6931, Accuracy: 0.5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

Predictions:
 [[0.]
 [0.]
 [0.]
 [0.]]


The code above demonstrates how to build and train a simple neural network using TensorFlow's Keras API. Here's a breakdown:

1.  **Prepare Sample Data**: We create a small dataset `X` (input features) and `y` (target labels). This is a classic XOR-like problem which is not linearly separable, requiring a hidden layer to solve.
2.  **Build the Neural Network Model**: We use `tf.keras.models.Sequential` to create a stack of layers.
    *   `Dense(2, activation='relu', input_shape=(2,))`: This is our first hidden layer. It has 2 neurons, uses the `ReLU` (Rectified Linear Unit) activation function, and specifies that the input will have 2 features (`input_shape=(2,)`).
    *   `Dense(2, activation='relu')`: This is our second hidden layer, also with 2 neurons and `ReLU` activation.
    *   `Dense(1, activation='sigmoid')`: This is the output layer. It has 1 neuron because we are predicting a single binary value (0 or 1), and `sigmoid` activation is used to squish the output between 0 and 1, making it suitable for binary classification probabilities.
3.  **Compile the Model**: Before training, the model needs to be compiled.
    *   `optimizer='adam'`: This is the algorithm used to update the network's weights during training. Adam is a popular and efficient choice.
    *   `loss='binary_crossentropy'`: This function measures how well the model is performing. For binary classification tasks, binary crossentropy is a standard choice.
    *   `metrics=['accuracy']`: This is what we want to monitor during training and evaluation.
4.  **Train the Model**: `model.fit(X, y, epochs=1000, verbose=0)` starts the training process. The model learns by iterating over the data multiple times (`epochs`).
5.  **Evaluate the Model**: After training, `model.evaluate()` calculates the loss and accuracy on the training data.
6.  **Make Predictions**: `model.predict()` uses the trained model to make predictions on new (or in this case, the same) input data.


### Data Flow During Training: Forward Pass and Backward Pass

Training a neural network involves a continuous cycle of two main phases for each batch of data:

1.  **Forward Pass (Prediction)**
2.  **Backward Pass (Learning/Weight Update)**

Let's break it down:

#### 1. Forward Pass (Input to Output)

During the forward pass, the input data travels through the network, layer by layer, to produce an output prediction.

*   **Input Layer**: The raw input data (e.g., `[0, 0]`, `[0, 1]`) is fed into the network.
*   **Hidden Layers**: For each neuron in a hidden layer:
    *   It receives inputs from all neurons in the previous layer.
    *   Each input is multiplied by its corresponding **weight**.
    *   These weighted inputs are summed up.
    *   A **bias** term is added to the sum.
    *   The result is passed through an **activation function** (e.g., ReLU), which introduces non-linearity, allowing the network to learn complex patterns.
    *   The output of this neuron then becomes an input to the neurons in the next layer.
*   **Output Layer**: The process continues until the final output layer. The output layer's neurons produce the network's prediction (e.g., a probability like 0.1 or 0.9). For our example, the sigmoid activation squashes the final value between 0 and 1, representing the probability of the input belonging to class 1.

At the end of the forward pass, the network has made a prediction based on its current set of weights and biases.

#### 2. Loss Calculation

Once a prediction is made, it is compared against the actual target value (the 'ground truth'). A **loss function** (e.g., binary crossentropy in our example) quantifies the discrepancy between the predicted output and the true output. A higher loss value means the prediction was far from the truth, while a lower value means it was closer.

#### 3. Backward Pass (Backpropagation - Error to Weights)

The backward pass is where the learning happens. The goal is to adjust the network's weights and biases to reduce the calculated loss.

*   **Gradient Calculation**: The loss value is propagated *backwards* through the network. Using a technique called **backpropagation**, the network calculates the **gradient** of the loss with respect to each individual weight and bias in every layer.
    *   The gradient tells us two things: the direction in which to change a weight/bias to reduce the loss, and the magnitude of that change.
    *   This is done using the chain rule of calculus, starting from the output layer and moving back to the input layer.
*   **Weight Update (Optimization)**: An **optimizer** (like Adam) takes these gradients and uses them to update the weights and biases of the network.
    *   It adjusts the weights and biases in the direction that minimizes the loss function. The `learning rate` (a parameter within the optimizer) determines the size of these adjustment steps.
    *   For example, if increasing a weight increases the loss, the optimizer will decrease that weight.

This entire process (forward pass, loss calculation, backward pass, weight update) is repeated for many **epochs** (full passes over the entire dataset) and often in smaller batches of data, allowing the network to iteratively refine its internal parameters and improve its ability to make accurate predictions.